name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update:
    strategy:
      matrix:
        node-version: [20.x]

    name: Update all dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm ci

      - run: pnpx pnpm-check-updates -u # Update dependencies
      - run: rm -Rf node_modules package-lock.json
      - run: pnpm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'build: update dependencies to the latest version'
          title: Update dependencies to the latest version
